apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: gluster-ssl-config
  labels:
    app: gluster-ssl-config
spec:
  selector:
    matchLabels:
      app: gluster-ssl-config
  template:
    metadata:
      labels:
        app: gluster-ssl-config
    spec:
      containers:
        - name: gluster-ssl
          image: busybox
          resources:
           limits:
             memory: 20Mi
             cpu: 0.5m
           requests:
             memory: 5Mi
             cpu: 0.5m
          command: ["/bin/sh", "-c"]
          args:
            - useradd  user;
              echo "check inint log";
              sleep infinity;
      initContainers:
        - name: gluster-init-container
          image: busybox
          resources:
           limits:
             memory: 50Mi
             cpu: 5m
           requests:
             memory: 20Mi
             cpu: 2m
          command: ["/bin/sh","/mnt/entrypoint/entrypoint.sh"]
          volumeMounts:
          - name: gluster-crt
            mountPath: /mnt/crt
          - name: etc-ssl
            mountPath: /etc/ssl/
          - name: entrypoint
            mountPath: /mnt/entrypoint/entrypoint.sh
            subPath: entrypoint.sh
          - name: secure-access
            mountPath: /var/lib/glusterd/
      volumes:
        - name:  gluster-crt
          secret:
            secretName: gluster-crt
            items:
            - key: glusterfs.pem
              path: glusterfs.pem
            - key: glusterfs.key
              path: glusterfs.key
            - key: glusterfs.ca
              path: glusterfs.ca
            defaultMode: 0600
        - name: etc-ssl
          hostPath:
            path: /etc/ssl
        - name: secure-access
          hostPath:
            path: /var/lib/glusterd/
        - name: entrypoint
          configMap:
            name: gluster-entrypoint-cm
