apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: gluster-ssl-config
  labels:
    app: gluster-ssl-config
spec:
  selector:
    matchLabels:
      app: gluster-ssl-config
  template:
    metadata:
      labels:
        app: gluster-ssl-config
    spec:
      containers:
        - name: gluster-ssl
          image: busybox
          command: ["/bin/sh","/mnt/entrypoint/entrypoint.sh"]
          #- sleep 5
          #- sh /mnt/entrypoint/entrypoint.sh
          volumeMounts:
         # - mountPath: /usr/local/apache2/htdocs
         #   name: gv0
          - name: gluster-crt
            mountPath: /mnt/crt
          - name: etc-ssl
            mountPath: /etc/ssl/
          - name: entrypoint
            mountPath: /mnt/entrypoint/entrypoint.sh
            subPath: entrypoint.sh
          - name: secure-access
            mountPath: /var/lib/glusterd/
      volumes:
      #- name: gv0 
      #  glusterfs:
      #    endpoints: glusterfs-cluster
      #    path: gv0/site1
      - name:  gluster-crt
        configMap:
           name: gluster-cm
      - name: etc-ssl
        hostPath:
           path: /etc/ssl
      - name: secure-access
        hostPath:
           path: /var/lib/glusterd/
      - name: entrypoint
        configMap:
           name: gluster-entrypoint-cm

