apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  labels:
    app: httpd_app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd_app
  template:
    metadata:
      labels:
        app: httpd_app
    spec:
      containers:
        - name: httpd-container
          image: httpd:latest
      #    command:
       #     - sleep
        #    - infinity
          ports:
            - containerPort: 80
          volumeMounts:
          - mountPath: /usr/local/apache2/htdocs
            name: gv0
        #- name: gluster-crt
        #  mountPath: /etc/ssl
        #- name: secure-acc
        #  mountPath: /var/lib/glusterd/secure-access
        #  subPath: secure-access
      volumes:
      - name: gv0 
        glusterfs:
          endpoints: glusterfs-cluster
          path: gv0/site1
      #- name:  gluster-crt
      #  configMap:
      #    name: gluster-cm
      #- name: secure-acc
      #  configMap:
      #    name: gluster-cm
---
