apiVersion: v1
kind: Service
metadata:
  name: glusterfs-cluster 
spec:
  ports:
  - port: 49153
---
apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster 
subsets:
  - addresses:
      - ip: 192.168.1.137
    ports:
      - port: 49153
  - addresses:
      - ip: 192.168.1.138
    ports:
      - port: 49153
  - addresses:
      - ip: 192.168.1.139
    ports:
      - port: 49153